Island:
  max_member_amount: 10
  chest:
    0:
      material: "DIAMOND"
    1:
      material: "IRON_INGOT"
  delete:
    spawn_location:
      world:
      x:
      y:
      z:
Ore:
  generation:
    - 'DIAMOND_ORE:1'
    - 'GOLD_ORE:30'
    - 'IRON_ORE:50'
Mines:
  mine:
    multiplier: 2
Mines-Configuration:
  delay: 10

Worth:
  spawner: 20
  emerald_block: 15
  diamond_block: 12
  iron_block: 9
  gold_block: 9
  redstone_block: 6
  lapis_block: 6
  quartz_block: 3
  coal_block: 1
